- ape_safe/multisend.py
> refactor: encode multisend `.as_transaction` without making a call

- ape_safe/accounts.py
- ape_safe/exceptions.py
- pyproject.toml
- setup.py
- tests/test_account.py
Adds a convenient way to create a transaction executed directly by the Safe for providers that support impersonated accounts
Example:
```py
receipt = contract.myMethod(..., sender=safe, impersonate=True)
```
A great way to use this is in temporary fork e.g.:
```py
with networks.fork():
receipt = contract.myMethod(..., sender=safe, impersonate=True)
receipt.show_trace()
...  # can validate side effects on the fork
```
> feat: impersonate safe [APE-873]

- ape_safe/accounts.py
safe delegates some of the calls to fallback handler. this fixes #9 by injecting abi from it to safe contract, enabling easier access to reading things like `safe.contract.VERSION()` or useful methods like `safe.contract.isValidSignature()`.
- fix: version for l2 contracts
- feat: add fallback_manager property
- feat: populate contract abi w fallback handler
fixes: #
> feat: fallback handler [APE-1109]

- ape_safe/accounts.py
I was having a bug where it would use keyfile accounts because of the address look-up, and that caused unexpected stdin to happen during tests. To alleviate, I made it use test accounts for local networks.
change net first and restrict if needed
tests work localloy now
> feat: restrict to test accounts in local networks [APE-1377]

- ape_safe/accounts.py
- ape_safe/exceptions.py
`no exception on stack` errors that would happen
use real errors.
`ValueError` made sense once.
`TypeError` made sense once.
A new custom error made sense once.
exceptions are better
> fix: empty raises [APE-1378]

- .pre-commit-config.yaml
- ape_safe/_cli/pending.py
- ape_safe/accounts.py
- ape_safe/client/mock.py
- pyproject.toml
- setup.py
- tests/conftest.py
- tests/integration/test_pending_cli.py
- tests/integration/test_safe_mgmt_cli.py
* fix: issue with propose execution, sender is required for initial proposal but doesnt mean we want to execute
* gas price was not settable
* account state was lost - i think only really matter with MockClient - but fixed
* missing success log when proposing
* filled in some tests surrounding the propose command but benefits i think all command
* handle some 0.7.1 upgrades
coing up next, ill look at approve, add tests, and fill in any gaps there.
> fix: various issues with propose cli

- .pre-commit-config.yaml
- ape-config.yaml
- ape_safe/_cli/click_ext.py
- ape_safe/_cli/pending.py
- ape_safe/accounts.py
- ape_safe/client/base.py
- ape_safe/exceptions.py
- setup.py
- tests/integration/test_pending_cli.py
- tests/integration/test_safe_mgmt_cli.py
Prevent some circular import issues.
~~Requires https://github.com/ApeWorX/ape/pull/1888~~
~~- [ ] New test cases have been added and are passing~~
> fix: circular import issues

- ape_safe/accounts.py
- ape_safe/client/__init__.py
- ape_safe/client/base.py
- ape_safe/client/mock.py
- tests/functional/test_account.py
NOTE: Is only a POV - I havent tested yet.
fixes: #36
> fix: estimate gas

- ape_safe/_cli/pending.py
- ape_safe/client/mock.py
- tests/integration/test_pending_cli.py
this ensures they are right and doesnt require anything weird
fixes: #35
> fix: use api to set confirmations on the tx after adding more

- ape-config.yaml
- ape_safe/client/__init__.py
https://blog.ethereum.org/2023/11/30/goerli-lts-update
https://www.alchemy.com/blog/goerli-faucet-deprecation
Goerli support on all networks is ending soon:
- February 16th - [Base Goerli](https://www.alchemy.com/blog/base-goerli-testnet-deprecation)
- March 7th - [Optimism Goerli](https://www.alchemy.com/blog/optimism-goerli-testnet-deprecation)
- March 18th - [Arbitrum Goerli](https://www.alchemy.com/blog/arbitrum-goerli-testnet-deprecation)
- April 1st - [Ethereum Goerli](https://www.alchemy.com/blog/ethereum-goerli-testnet-deprecation)
- April 6th - [Polygon zkEVM Goerli](https://www.alchemy.com/blog/polygon-zkevm-cardona-is-live)
- April 11th - [Starknet Goerli](https://www.alchemy.com/blog/starknet-sepolia-is-live)
- April 13th - [Polygon …
> refactor: remove goerli

- ape_safe/_cli/safe_mgmt.py
- ape_safe/client/__init__.py
- ape_safe/client/base.py
just changed the API route
fixes: #46
> fix: update for API route change

- ape_safe/client/__init__.py
Noticed in the Safe API transaction service code that a User Agent string is appended to the transaction request when you make a transaction, so I added it
Leverage Ape core's user agent string, as well as do a little researching on how it is supposed to be done
Make a transaction on a testnet safe
~~- [ ] New test cases have been added and are passing~~
> refactor(API): add a user agent

- ape-config.yaml
- ape_safe/accounts.py
- tests/integration/test_pending_cli.py
gas price has a different meaning in safe transactions. it is used to pay the relayer which is not what we want.
https://github.com/safe-global/safe-smart-account/blob/a9e3385bb38c29d45b3901ff7180b59fcee86ac9/contracts/Safe.sol#L180-L182
fixes inability to execute submitted transactions.
force `gas_price` to zero
> fix: safe tx gas price should be zero

- ape_safe/_cli/pending.py
- ape_safe/accounts.py
see also https://docs.safe.global/advanced/smart-account-signatures
sign eip-712 message instead of defunct message.
if you follow the naming in [safe docs](https://docs.safe.global/advanced/smart-account-signatures), i have switched `eth_sign` signature for ecdsa signature.
it has also allowed to remove the method to adjust `v` of the signature.
fixes: #54
replace signing of `safe_tx_hash` with signing of `safe_tx`.
```python
In [9]: yes.transfer(dev, '1 ether', nonce=1, sender=safe, submit=False)
Signing EIP712 Message
Domain
Chain ID: 81457
Contract: 0x...
Message
to: 0x1a49351bdB4BE48C0009b661765D01ed58E8C2d8
value: 0
data: b'\xa9\x05\x9c\xbb\...'
operation: 0
safeTxGas: 0
baseGas: 0
gasPrice: 0
gasToken: 0x0000000000000000000000000000000000000000
refundReceiver: …
```
> feat: sign eip-712 message instead of hash

- .github/workflows/test.yaml
> chore: move macos image back to latest

- tests/conftest.py
- tests/integration/conftest.py
fixes: https://github.com/ApeWorX/ape/issues/2133
I believe as a result of this PR, tests even in CI run a lot faster.
Add delegates from last week total duration: 12m 35s
This PR total duration: 3m 43s
> test: adjust tests to not double-download Safe contracts

- .pre-commit-config.yaml
- ape_safe/__init__.py
- ape_safe/_cli/click_ext.py
- ape_safe/_cli/pending.py
- ape_safe/accounts.py
- ape_safe/client/base.py
- ape_safe/client/mock.py
- ape_safe/config.py
- ape_safe/exceptions.py
- ape_safe/multisend.py
- ape_safe/utils.py
- setup.cfg
- setup.py
> perf: make `ape --help` faster  when `safe` installed pt. 2

- .github/workflows/test.yaml
- ape_safe/_cli/pending.py
- ape_safe/accounts.py
- ape_safe/client/__init__.py
- ape_safe/client/mock.py
- ape_safe/client/types.py
- ape_safe/utils.py
- pyproject.toml
- setup.py
I think this causes problems in web3 7 environment, as seen in another test run.
> fix: use `to_hex()` instead of `bytes.hex()`

- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- .gitignore
- ape-config.yaml
- ape_safe/accounts.py
- ape_safe/factory.py
- ape_safe/packages.py
- pyproject.toml
- scripts/build.py
- setup.py
- tests/conftest.py
- tests/functional/test_account.py
- tests/integration/conftest.py
- tests/integration/test_pending_cli.py
- tests/integration/test_safe_mgmt_cli.py
This PR adds some updates in order to support the multiple versions of the Safe multisig contracts
fixes: #29
> feat: support all versions of Safe

- .github/workflows/test.yaml
- ape_safe/_cli/__init__.py
- ape_safe/_cli/delegates.py
- ape_safe/accounts.py
- ape_safe/client/__init__.py
- ape_safe/client/base.py
- ape_safe/client/mock.py
- ape_safe/client/types.py
- tests/conftest.py
- tests/functional/test_delegates.py
Adds support for delegates to the Client classes (including MockClient), the CLI (via `ape safe delegates ...`), as well as to the main accounts class (`SafeAccount.propose_safe_tx` and `SafeAccount.propose`)
fixes: #16
> feat: add delegates

- README.md
- ape_safe/accounts.py
- ape_safe/config.py
- ape_safe/types.py
Noticed that it wasn't really possible to config this plugin for a cloud environment where an image didn't already have a Safe loaded into the `~/.ape` data folder, so this adds support for that
Took inspiration from `ape-tokens` a bit
Add to your config or specify via env var and try it
~~- [ ] New test cases have been added and are passing~~
> feat: allow configuring Safes for cloud use

- .github/workflows/test.yaml
- ape_safe/_cli/safe_mgmt.py
- ape_safe/accounts.py
- ape_safe/client/__init__.py
- ape_safe/client/base.py
- ape_safe/client/mock.py
- ape_safe/client/types.py
- ape_safe/exceptions.py
- tests/functional/test_account.py
- Use new gateway URL https://safe-client.safe.global/ instead of network-specific URLs
- Add deployed_chain_ids property to SafeAccount for easier chain access
- Add get_client method with optional chain_id parameter
- Update URL paths to include chain ID for multichain gateway
- Update CLI to use new client interface
- Improve naming and documentation
Fixes #56
- Run the tests
- Try to access a Safe on multiple chains
> feat: refactor safe client to use multichain gateway

- setup.py
v0.8.13 failed to publish because we have a pinned dep to a branch
~~- [ ] New test cases have been added and are passing~~
> fix(Deps): pin sphinx-ape to latest release

- ape_safe/packages.py
Noticed that we were incorrectly using the address for `MultiSend` instead of `MultiSendCallOnly` for Safe versions > v1.1.1
fixes: #87
> fix(Packages): incorrectly using MultiSend address for v1.3.0+
